Problem 7.  Consider the simple neuron in Stevens Fig. 6.2, with tanh() activation and initial parametrs w=2 and b=0 (note this is different from the textbook). Given the following three training data, (x,o) = { (20, 1), (10, 0), (0, -1) }, calculate the output of the network 

In [1]:
%matplotlib inline
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
x = [20.0, 10.0, 0.0]
y = [1.0, 0.0, -1.0]
x = torch.tensor(x).unsqueeze(1)
y = torch.tensor(y).unsqueeze(1)
x.requires_grad_(True)

tensor([[20.],
        [10.],
        [ 0.]], requires_grad=True)

In [3]:
#network
tanh_model = nn.Sequential(
            nn.Linear(1, 1), # <1>
            nn.Tanh())

In [4]:
# Set the model parameters w = 2, b = 0
with torch.no_grad():
    tanh_model[0].weight.fill_(2.0)  # Set the weight w = 2
    tanh_model[0].bias.fill_(0.0)    # Set the bias b = 0

In [5]:
#output of network
output = tanh_model(x)
output

tensor([[1.],
        [1.],
        [0.]], grad_fn=<TanhBackward0>)

Problem 8: Now calculate the squared error for the above network and each of the three training data points. 

In [6]:
def loss_fn(x, y):
    squared_errors = (y - x)**2
    return squared_errors

In [7]:
squared_errors = loss_fn(output,y)
squared_errors

tensor([[0.],
        [1.],
        [1.]], grad_fn=<PowBackward0>)

In [8]:
sum_squared_errors = squared_errors.sum()
sum_squared_errors

tensor(2., grad_fn=<SumBackward0>)

In [9]:
optimizer = optim.SGD(
    tanh_model.parameters(),
    lr=0.1)

Problem 11: Calculate the gradients for each of these training data points.

In [10]:
optimizer.zero_grad()
sum_squared_errors.backward()
optimizer.step()

In [11]:
print(x.grad)

tensor([[0.],
        [0.],
        [4.]])


Problem 12: Sum up the gradients for all 3 data points. Given a learning rate (step size) of 0.1, calculate the new parameters w and b.

In [12]:
print(tanh_model[0].weight)

Parameter containing:
tensor([[2.]], requires_grad=True)


In [13]:
print(tanh_model[0].bias)

Parameter containing:
tensor([-0.2000], requires_grad=True)
